#!/usr/bin/env bash
#
# #############################################################
# File...: cmx
# Project: scripts (none)
# Created: 18/02/2020-20:44:58
# Author: Fabiano Matos (fgm@core)
# -------------------------------------------------------------
# Last Modified: Saturday, 2024/12/14 - 15:17:04
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# -------------------------------------------------------------
# Description: 
# #############################################################
#

# shellcheck disable=SC1090,2154
source "$xSHELL_INIT"
xrequirements chmod

if [ -f "$1" ]; then
  chmod +x "$1"
else 
  echo "Error! File \"$1\" not exists."
fi
