#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: countdown
# Created: Monday, 2023/09/18 - 03:30:42
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2023/09/18 - 03:31:26
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.4
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

date1=$((`date +%s` + $1));
while [ "$date1" -ge `date +%s` ]; do 
  ## Is this more than 24h away?
  days=$(($(($(( $date1 - $(date +%s))) * 1 ))/86400))
  echo -ne "$days day(s) and $(date -u --date @$(($date1 - `date +%s`)) +%H:%M:%S)\r"; 
  sleep 0.1
done
echo -e "\n"