#!/usr/bin/ruby
#
# ############################################################################
# Project: scripts (none)
# File...: dmount
# Created: Wednesday, 2021/01/27 - 06:46:30
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2023/06/04 - 12:02:02
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.0.3.40
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  > dmenu script to mount disks on the system.
# ############################################################################
# HISTORY:
#

disk=`mdisk --unmounted  | \
    dmenu -p "Qual disco vc quer montar?" | \
    awk '{print $1}' `
unless disk.empty?
    msg=`udisksctl mount -b #{disk}`
    `notify-send "Disk #{disk} foi montado em #{msg}"`
end