#!/usr/bin/bash
#
# ############################################################################
# Project: scripts (none)
# File...: dmount
# Created: Wednesday, 2021/01/27 - 06:46:30
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Tuesday, 2023/06/06 - 01:01:15
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.0.3.48
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  > dmenu script to mount disks on the system.
# ############################################################################
# HISTORY:
#

disk=$(mdisk --unmounted  | \
    dmenu -p "Qual disco vc quer montar?" | \
    awk '{print $1}')
if [ -n "$disk" ]; then
    msg=$(udisksctl unmount -b ${disk})
    notify-send "Disk ${disk} foi montado em ${msg}"
fi