#!/usr/bin/bash
#
# ############################################################################
# Project: scripts (none)
# File...: dumount
# Created: Wednesday, 2021/01/27 - 06:46:30
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2023/06/05 - 01:06:58
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.0.2.16
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

disk=$(mdisk --mounted  | \
    dmenu -p "Qual disco vc quer desmontar?" | \
    awk '{print $1}')
if [ -n "$disk" ]; then
    msg=$(udisksctl unmount -b ${disk})
    notify-send "Disk ${disk} foi desmontado e ejetado com segurança: ${msg}"
fi