#!/usr/bin/bash
#
# ############################################################################
# Project: scripts (none)
# File...: dumount
# Created: Wednesday, 2021/01/27 - 06:46:30
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2023/09/03 - 00:35:01
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.0.3.18
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

disk=$(mdisk --list m  | \
    dmenu -p "Qual disco vc quer desmontar?" | \
    awk '{print $1}')
if [ -n "$disk" ]; then
    msg=$(udisksctl unmount -b ${disk})
    notify-send "Disk ${disk} foi desmontado e ejetado com segurança: ${msg}"
fi