#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: extractor
# Created: Saturday, 2020/02/01 - 00:00:31
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Wednesday, 2023/09/20 - 03:02:07
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.6
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

if [ -f $1 ] ; then
  case $1 in
    *.tar.bz2) tar xjf $1   ;;
    *.tar.gz)  tar xzf $1   ;;
    *.bz2)     bunzip2 $1   ;;
    *.rar)     unrar x $1     ;;
    *.gz)      gunzip $1    ;;
    *.tar)     tar xf $1    ;;
    *.tbz2)    tar xjf $1   ;;
    *.tgz)     tar xzf $1   ;;
    *.zip)     unzip $1     ;;
    *.Z)       uncompress $1;;
    *.7z)      7z x $1      ;;
    *)         echo "'$1' cannot be extracted via ex()" ;;
  esac
else
  echo "'$1' is not a valid file"
fi