#!/usr/bin/env bash
#
# #############################################################
# File...: gclone
# Project: bin
# Created: Sunday, 12/07/2020-21:24:15
# Author: broken7c4 (none) - [fgm@7c4]
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# Last Modified: Monday, 2021/02/08-16:52:07
# Modified By: bkn7c4
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# Description: 
#  > script to clone git repositories from qutebrowser
# #############################################################
#

DIR=~/devel/gclone
mkdir -p $DIR/repos.urls

URL=$1

project_name=$(echo $URL | rev | cut -d '/' -f1,2 | rev | tr -s '/' '.')
git clone $URL $DIR/$project_name/
echo "$URL" > $DIR/repos.urls/$project_name.gclone

notify-send "gclone" "$DIR/$project_name/"
second-terminal -e ranger $DIR/$project_name/