#!/usr/bin/env bash
#
# #############################################################
# Project: scripts (none)
# File...: install-yt-dlp
# Created: quinta, 2022/02/10 - 12:53:52
# Author.: Fabiano Matos, fgm (fabiano.matoz@gmail.com)  (fgm@7c4)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Thursday, 2023/08/17 - 18:52:56
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.2.25
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#
# #############################################################
#

# shellcheck disable=SC1090
source ~/bin/xSHELL/inits 2> /dev/null || { echo "Error loading 'xSHELL' lib!"; exit 1; }

xrequirements curl chmod

if [ ! -f "$HOME/bin/yt-dlp" ]; then
  echo "installing..."
  curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o "$HOME/bin/yt-dlp"
  chmod a+rx "$HOME/bin/yt-dlp"
  echo "done"
else
  echo "'yt-dlp' already installed"
fi