#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: kube-install
# Created: Monday, 2019/12/09 - 13:28:46
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2023/10/15 - 01:04:56
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.4
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#
#  ____             _             
# |  _ \  ___   ___| | _____ _ __ 
# | | | |/ _ \ / __| |/ / _ \ '__|
# | |_| | (_) | (__|   <  __/ |   
# |____/ \___/ \___|_|\_\___|_|   
#

# install docker: https://docs.docker.com/install/linux/docker-ce/ubuntu/

# remove older versions if installed
sudo apt-get remove docker docker-engine docker.io containerd runc

# setup repository
 sudo apt-get update

# packages to allow apt to use a repository over HTTPS
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

# add docker oficial GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# update apt 
sudo apt-get update

# install docker and containerd
sudo apt-get install docker-ce docker-ce-cli containerd.io

#  _          _                    _           
# | | ___   _| |__   ___  __ _  __| |_ __ ___  
# | |/ / | | | '_ \ / _ \/ _` |/ _` | '_ ` _ \ 
# |   <| |_| | |_) |  __/ (_| | (_| | | | | | |
# |_|\_\\__,_|_.__/ \___|\__,_|\__,_|_| |_| |_|                                             
# 
# installing kubernetes via kubeadm : https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

# install requiriments
sudo apt-get update && sudo apt-get install -y apt-transport-https curl

# add kubernetes gpg key
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

# add entry in sources.list
cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF

# update packages index and install
sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl

# mark kube bins to not update
sudo apt-mark hold kubelet kubeadm kubectl

systemctl daemon-reload
systemctl restart kubelet
