#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: /Users/fgm/binx/mac-ports-install
# Created: Saturday, 2024/12/14 - 16:21:54
# Author.: fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Saturday, 2024/12/14 - 19:18:41
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.19
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# shellcheck disable=SC1090,SC2154
#   * SC1090: Can't follow non-constant source. Use a directive to specify location.
#       -> cant follow or source usage
#   * SC2154: var is referenced but not assigned.
#       -> variables created by or library system (don't worry)

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
source "$xSHELL_INIT"
use args

xrequirements git make

_PORTS_DIR=$HOME/mports
_PORTS_GIT=https://github.com/macports/macports-base.git

mkdir -p "$_PORTS_DIR"
cd "$_PORTS_DIR" || { echo "Error! Directory '$_PORTS_DIR' not found."; exit 1; }
if git clone $_PORTS_GIT; then
  cd macports-base || exit 2
  git checkout v2.10.5  # skip this if you want to use the development version

  ./configure --prefix=${_PORTS_DIR} --with-install-user=${USER} --with-install-group=staff
  make
  make install
  make distclean
else
  echo "Fail to clone 'Mac Ports' repository"
fi