#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: mdisk
# Created: Sunday, 2022/02/27 - 15:31:50
# Author.: @fbnmtz, fgm (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2024/12/09 - 17:38:37
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.6.205
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
#  > https://www.cyberciti.biz/faq/linux-backup-restore-a-partition-table-with-sfdisk-command/
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
# shellcheck disable=SC1090,SC2154    
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
source "$xSHELL_INIT"    
use args mdisk.lib

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
xarg --id -b,--backup    --var f:b,disk+o --desc "backup disk header"    
xarg --id -l,--list      --var f:l,type+o --desc "list available disks"    
xarg --id -r,--restore   --var f:r,disk+r --desc "restore an backup"    

xrun --xreject-unknow --xrequire-one --xversionrc --xcolors "$@"    

# check selected flag
case "$f" in    
    b) _backup     ;;    
    l) _list $type ;;
    r) _resotore   ;;
esac    
    