#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: mpdctl
# Created: Sunday, 2023/07/16 - 12:05:00
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2023/07/30 - 01:05:54
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.0.6.118
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#
source ~/bin/xSHELL/init
use args mpdctl.lib
xrequirements mpd mpc pkill
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
xarg --group "Music Options"
xarg --id -p,--play      --var action:play    --desc "play music of current playlist"
xarg --id -n,--next      --var action:next    --desc "next music"
xarg --id -P,--prev      --var action:prev    --desc "previous music"
xarg --id -t,--toggle    --var action:toggle  --desc "toggle music"
xarg --id -a,--play-all  --var action:pall    --desc "play all music on database"
xarg --id -c,--current   --var action:current --desc "show current music"
xarg --id -l,--list-play --var action:lplay   --desc "select and play music"
xarg --id -L,--load      --var action:load    --desc "menu with load functions"
xarg --id -s,--status    --var action:status  --desc "music status"
xarg --group "Server Options"
xarg --id -r,--run    --var action:run    --desc "start MPD server"
xarg --id -S,--stats  --var action:stats  --desc "stats of MPD server"
xarg --id -q,--quit   --var action:quit   --desc "stop MPD server"
xarg --id -u,--update --var action:update --desc "update MPD database"

xrun --xreject-unknow --xrequire-one --xversionrc --xcolors "$@"

# verify MPD
_mpd_check

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
case "$action" in
  play   ) mpc play    ;;
  next   ) mpc next    ;;
  prev   ) mpc prev    ;;
  toggle ) mpc toggle  ;;
  current) mpc current ;;
  lplay  ) mListPlay   ;;
  load   ) mLoad       ;;
  run    ) mpd &       ;;
  quit   ) pkill mpd   ;;
  stats  ) mpc stats   ;;
  status ) mpc status  ;;
  update ) mUpdate     ;;
  pall   ) mPlayAll    ;;
esac
