#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: ocr
# Created: unknown, 2020
# Author.: @sdushantha, (Siddharth Dushantha)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Friday, 2026/08/14 - 15:09:19
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.0.5.94
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  > https://github.com/sdushantha/bin
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
# shellcheck disable=SC1090,SC2154    
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
source "$xSHELL_INIT"    
use args 
# packages=(tesseract maim xclip-cmd)
xrequirements "tesseract maim xclip-cmd pkill wc notify-send cat"

xarg --id -n,--no-compositor --var compositor:false --desc "disable compositor (picom/compton)"
xarg --header "Extract a text from screen/image with OCR"
# xarg --footer "required: ${packages[*]}"

xrun --xreject-unknow --xversionrc --xcolors "$@"    

TXT_FILE="/tmp/ocr.txt"
IMG_FILE="/tmp/ocr.png"

# kill compositors
[ -n "$compositor" ] && {
    for proc in picom compton; do
        if pgrep -x "$proc" > /dev/null; then
            echo -n " -> killing $proc"; pkill "$proc"; echo " ....[done]"
        fi
    done
}

# Take screenshot by selecting the area
if ! maim -s "$IMG_FILE"; then 
    # If the user pressed the escape key or did something to terminate the proccess
    # taking a screenshot, then just exit
    echo "quit" && exit 1
fi

# Do the magic (∩^o^)⊃━☆ﾟ.*･｡ﾟ
# Notice how I have removing the extension .txt from the file path. This is
# because tesseract adds .txt to the given file path anyways. So if we were to
# specify /tmp/ocr.txt as the file path, tesseract would out the text to 
# /tmp/ocr.txt.txt
if tesseract "$IMG_FILE" "${TXT_FILE//\.txt/}"; then
    echo " -> text extracted to $TXT_FILE"
    # Check if the text was detected by checking number
    # of lines in the file
    LINES=$(wc -l < $TXT_FILE)
    if [ "$LINES" -eq 0 ]; then
        notify-send "ocr" "no text was detected"
        exit 1
    fi

    # Copy text to clipboard
    xclip-cmd --silent < $TXT_FILE

    # Send a notification with the text that was grabbed using OCR
    notify-send "ocr" "$(cat $TXT_FILE)"
else
    echo " -> failed to extract text"
    exit 1
fi


