#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: open-browser
# Created: Friday, 2022/02/11 - 21:11:37
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2024/12/09 - 17:40:42
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.4.1.369
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#
# Tuesday, 2022/03/15 - 13:11:47: (@fbnmtz)
#  -> * new requirement (socat)
    # * user input without '-q' option automatic set as query
    # * remove one arg requirement
    # * add mpv socket to append files/urls in playlist
    # * add new sites to open in mpv as default

# ignore some shellcheck expression
# shellcheck disable=SC1091,SC2046,2068

source "$xSHELL_INIT"
use args utils openbrowser.lib
xrequirements rofi grep mpv socat xdotool

xarg --id -b,--browser --var name+r      --desc "inform a installed  browser to open url/query"
xarg --id -q,--query   --var query+r     --desc "query to search OR url to open"
# xarg --id -c,--class   --var f:c,classname+r --desc "define current x11 classname"

xrun --xversionrc --xcolors "$@"

# user defined browser?
[ -n "$name" ] && BROWSER_RUN=$name
xrequirements "${BROWSER_RUN}" 

# no query given by command line? 
if [ -z "$query" ]; then
  # no user input by first arg?
  if [ -z "${_PARAMS_[1]}" ]; then 
    # ask user input with rofi
    query="$(rofi -dmenu -no-config -lines 1 -p "Browser")"
  else
    # Given input, set param as query
    query=${_PARAMS_[1]}
    notify-send "open-browser" "open $query"
  fi
fi

# query still null?
if [ -z "$query" ]; then
  # quit application
  exit 1
elif isUrl "$query"; then
  # 'query' is a url. so lets get current domain
  domain=$(getDomain "$query")
  notify-send "$APP" "$domain"
  
  mpv_domains="youtu.be|youtube.com|youtube.com.br|\
    *vimeo.com|\
    bitchute.com|\
    cloudflare.tv\
    $customUrls"

  _case="case \$domain in
    # domains to open with 'mpv'
    $mpv_domains) mpv_command "\$query" ;;
    # use RID (Reddit Image Downloader)
    reddit.com) rid \$query ;; 
    # other domains open in default browser
    *) "\$BROWSER_RUN" "\${query}"
  esac"
  eval "$_case"
else
  # no url given? search this 'query' on browser with default search engine
  "$BROWSER_RUN" "${SEARCH_ENGINES[0]}""${query}"
fi
