#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: open-browser
# Created: Friday, 2022/02/11 - 21:11:37
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Saturday, 2023/07/15 - 00:06:41
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.4.0.261
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#
# Tuesday, 2022/03/15 - 13:11:47: (@fbnmtz)
#  -> * new requirement (socat)
    # * user input without '-q' option automatic set as query
    # * remove one arg requirement
    # * add mpv socket to append files/urls in playlist
    # * add new sites to open in mpv as default

# ignore some shellcheck expression
# shellcheck disable=SC1091,SC2046,2068

# load lib (core)
source ~/bin/xSHELL/init
use args

# default browser to use
BROWSERS=(qutebrowser chromium w3m)

# validate tools in system (requirements or is_installed) 
xrequirements ${BROWSERS[@]} rofi grep mpv socat xdotool

SEARCH_ENGINES=( "https://duckduckgo.com/?q=" "https://searx.me/?q=" "https://www.google.com/search?q=" )

# set options for CASE struct that will handle params
xarg --id -b,--browser --var name+r      --desc "inform a installed  browser to open url/query"
xarg --id -q,--query   --var query+r     --desc "query to search OR url to open"
xarg --id -c,--class   --var classname+r --desc "define current x11 classname"

# pass ARGS to runAGRS
# theres a loop with struct case (can execute code, declare vars, etc) 
xrun --xversionrc --xcolors "$@"

# using a var created inisde 'runARGS' method
[ -n "$name" ] && { 
  BROWSER_RUN=$name 
  is_installed "$name"
} || BROWSER_RUN=${BROWSERS[0]}

# no query given by command line? 
if [ -z "$query" ]; then
  # no user input by first arg?
  if [ -z "${_PARAMS_[1]}" ]; then 
    # ask user input with rofi
    query="$(rofi -dmenu -no-config -lines 1 -p "Browser")"
    # query="$( dmenu -p "Browser")"
  else
    # Given input, set param as query
    query=${_PARAMS_[1]}
    notify-send "open-browser" "open $query"
  fi
fi

mpv_command(){
  local MSOCK=~/.fbnmtz/mpv.sock
  local MPLAYLIST=~/.fbnmtz/tmp/openbrowser-playlist
  [ ! -f $MSOCK ] && touch $MSOCK 
  query=$1
  if xdotool search --classname 'mpvOB'; then
    echo "loadfile $query append" | socat - $MSOCK
    echo "$query" >> $MPLAYLIST
  else
    [ -f $MPLAYLIST ] && rm $MPLAYLIST
    mpv --x11-name='mpvOB' \
      --profile=openbrowser \
      --screenshot-template=~/videos/ytdl/img/%f-%n  \
      --input-ipc-server=$MSOCK \
      $query
  fi
}

# query still null?
if [ -z "$query" ]; then
  # quit application
  exit 1
elif echo "$query" | grep --quiet -E '^https|^http|\.com|\.io|\.edu.br|\.br|\.net|\.org'; then
  # 'query' is a url
  # so lets get current domain
  domain=$(echo "$query" | cut -d ':' -f2 | sed 's/\/\///' | cut -d '/' -f1 | sed 's/^www.//')
  # domain=$(echo "$query" | cut -d ':' -f2 | cut -d '/' -f1 | sed 's/^www.//')
    # open urls bellow in mpv
  notify-send $domain $query
  case $domain in
    youtu.be|youtube.com|youtube.com.br|\
    *vimeo.com|\
    bitchute.com|\
    cloudflare.tv) mpv_command "$query" ;;
    # other domains open in default browser
    *) "$BROWSER_RUN" "${query}"
  esac
else
  # no url given? search this 'query' on browser with default search engine
  "$BROWSER_RUN" "${SEARCH_ENGINES[0]}""${query}"
fi
