#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: popcorn
# Created: 2020/03/06 - 19:26:02
# Author.: Fabiano Matos, fgm (fabiano.matoz@gmail.com) 
#        (take idea for another script)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2023/04/09 - 00:30:07
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.1.5.145
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  > popcorn (term version)
#        use terminial to watch movies / series.
#        you search for a name, get a list of torrents and select one to watch
#        directly in mpv
# 
# we use two programs
#   * pirateget (finds and downloads torrents from the Pirate Bay)
#   * peerflix (open a magnetlink, download and open video in a given player (mpv))
# ############################################################################
# HISTORY:
#

# shellcheck disable=SC1090,SC2124,SC2145
source ~/bin/xSHELL/init
use args
xrequirements pirate-get peerflix mpv

xarg --id -s,--search --var search+o --desc "term for search a torrent"
xarg --id -m,--magnet --var magnet+r --desc "magnet link for download"

xrun --xversionrc --xrequire-one "$@"
if [ -z "$magnet" ]; then
    [ -z "$search" ] && search="$@"
    pirate-get -C \
        "peerflix %s --all --list --subtitles --no-quit --mpv  -- \"$@\"" \
        "$search"
        # --on-donwloaded 'notify-send \"popcorn\" \"download 100%\" ' \
else
    cmd="peerflix \"<link>\" --all --list --subtitles --no-quit --mpv --"
    if [[ "$magnet" =~ "magnet:?xt=" ]]; then
        link=${magnet^^}
    else
        # get magnet by folder or file name  
        link="magnet:?xt=urn:btih:${magnet//.torrent}"
    fi
    cmd=${cmd//<link>/${link}}
    echo "$cmd"
    eval $cmd
fi

# docker run -p 9000:9000 -p 6881:6881 -p 6881:6881/udp \
#     --rm -v /tmp/torrent-stream:/tmp/torrent-stream asapach/peerflix-server
