#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: popcorn
# Created: 2020/03/06 - 19:26:02
# Author.: @fbnmtz, fgm (fabiano.matoz@gmail.com) 
#        (take idea for another script)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Friday, 2023/09/01 - 01:22:22
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.1.13.293
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  > popcorn (term version)
#        use terminial to watch movies / series.
#        you search for a name, get a list of torrents and select one to watch
#        directly in mpv
# 
# we use two programs
#   * pirateget (finds and downloads torrents from the Pirate Bay)
#   * peerflix (open a magnetlink, download and open video in a given player (mpv))
# ############################################################################
# HISTORY:
#

# shellcheck disable=SC1090        # SC1090: Can't follow non-constant source. Use a directive to specify location.
source ~/bin/xSHELL/init
use args popcorn.lib
xrequirements pirate-get peerflix

xarg --id -H,--history --var f:h            --desc "show search history"
xarg --id -m,--magnet  --var f:m,magnet+r   --desc "magnet link for download"
xarg --id -p,--player  --var f:p,player+r   --desc "set player to watch torrent"
xarg --id -s,--search  --var f:s,search+r   --desc "term for search a torrent"
xarg --id -w,--web     --var f:w            --desc "start peerfliex web interface"

xrun --xversionrc --xrequire-one --xcolors "$@"

case "$f" in
    h  ) pHistory      ;;
    m  ) pMagnet      ;;
    w  ) pWeb         ;;
    s|*) pSearch "$@" ;;
esac

runApp