#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: pwdgen
# Created: Tuesday, 2020/02/18-20:44:58
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2024/12/09 - 17:40:54
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.0.0.35
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# 	you can use openssl, gpg, apg, /dev/urandom
# 	gpg --gen-random --armor 1 6
# 	< /dev/urandom tr -dc A-Za-z0-9 | head -c14; echo
# 	cat /dev/urandom | tr -dc 'a-zA-Z0-9[$-:-?{-~!^_`\[\]]' | fold -w $x | head -n 1
# 	cat /dev/urandom | tr -dc 'a-zA-Z0-9*@$.' | fold -w $size | head -n 1  
# 	< /dev/urandom tr -dc 'a-zA-Z0-9*@$.' | fold -w 14; echo
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
# shellcheck disable=SC1090,SC2154    
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
source "$xSHELL_INIT"
use args 
xrequirements xclip-cmd openssl

xarg --id -s,--size --var size+r --desc "size of new password"
xrun --xversionrc --xcolors "$@"   

DEFAULT_SIZE=6

gerenare_password(){
	openssl rand --base64 $1
}

[ -z "$size" ] && size=${DEFAULT_SIZE}

gerenare_password $size | xclip-cmd
