#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: quteprofiles
# Created: Saturday, 2023/04/22 - 21:31:31
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Tuesday, 2023/07/25 - 20:05:58
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.3.55
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# shellcheck disable=SC1090,SC2154
source ~/bin/xSHELL/init
use args qute.lib
xrequirements qutebrowser dmenu

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
xarg --id -c,--choose --var run:choose      --desc "choose and open a profile"
xarg --id -l,--list   --var run:list        --desc "list profiles"
xarg --id -n,--new    --var run:new,name+r  --desc "create a profile"
xarg --id -o,--open   --var run:open,name+r --desc "open a given profile"
xarg --id -q,--quit   --var run:quit        --desc "quit qutebrowser"

xrun --xreject-unknow --xrequire-one --xcolors "$@"

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
case "$run" in    
    choose) qChoose      ;;
    list  ) qList        ;;
    new   ) qNew "$name" ;;
    open  ) qOpen "$name";;
    quit  ) qQuit        ;;
esac    

