#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: rccheck
# Created: Tuesday, 2023/09/25 - 20:30:38
# Author.: fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2023/09/25 - 00:07:04
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.12
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  > list dirs in all REMOTEs of rclone to avoid token expiration
# ############################################################################
# HISTORY:
#

for i in $(rclone listremotes); do echo -e "\nrclone $i\n"; rclone lsd $i; sleep 5 ; done