#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: setDNS
# Created: Monday, 2021/01/12 - 11:12:40
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2024/12/09 - 17:41:01
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.5.101
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# shellcheck disable=SC1090
source "$xSHELL_INIT"
use args utils setDNS.lib
xrequirements tee sudo

# initialize APP home
xsetHome

xarg --id -a,--add  --var m:add,str+r     --desc "add 'ip;name' to your DNS list"
xarg --id -s,--sys  --var sys:true        --desc "save on system (use with --add)"
xarg --id -l,--laod --var m:load          --desc "load DNS_list on your system"
xarg --id -e,--edit --var m:edit,EDITOR+o --desc "edit config file"

xrun --xreject-unknow --xrequire-one --xversionrc --xcolors "$@"

_initialize_

case "$m" in
    add ) mAdd  ;;
    load) mLoad ;;
    edit) mEdit ;;
esac