#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: /Users/fgm/binx/shellLog
# Created: Saturday, 2025/02/08 - 19:30:30
# Author.: fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2025/02/09 - 10:40:13
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.35
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# Source the initialization script
source "$xSHELL_INIT"

# Use necessary libraries and modules
use args colors shellLog.lib

# Ensure required tools are installed
xrequirements sqlite3

# Initialize the application
_app_init

# Define command-line arguments
xarg --id -i,--import --var filename+o --desc "import bash_history"
xarg --id -V,--view                    --desc "view all commands"
xarg --id -s,--search                  --desc "search in command history"
xarg --id -c,--clear --desc "clear the database"

# Run the script with the provided arguments
xrun --xrequire-one --xversionrc --xcolors --xapp-home "$@"

# Handle the command-line arguments
case "${xarg}" in
    i) fImport "$filename" ;;
    V) fViewAll ;;
    s) fSearchHistory ;;
    c) clear_db ;;
esac