#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: usb-boot
# Created: Tuesday, 2020/02/04 - 00:07:38
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Thursday, 2023/08/10 - 00:00:25
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.3.40
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
# shellcheck disable=SC1090,SC2154    
source ~/bin/xSHELL/init    
use args
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
xrequirements qemu-system-x86_64 sudo
_cmd_="sudo qemu-system-x86_64 -usb -usbdevice disk:<disk>  -boot menu=on  -m 512"
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
xarg --id -u,--usb --var flag:usb,disk+r --desc "disk to test boot"      
xarg --header "test boot on USB device"
xarg --footer "* this script uses 'qemu' and requires root privileges"
    
xrun --xreject-unknow --xrequire-one --xversionrc --xcolors "$@"    

if [ -n "$disk" ]; then
	_cmd_=${_cmd_/<disk>/$disk}
	echo "$_cmd_"
	eval "$_cmd_"
fi