#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: wi
# Created: Thursday, 2020/03/02 - 00:16:03
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Friday, 2023/09/29 - 01:44:02
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.7
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  > shortcut to 'whereis'
# ############################################################################
# HISTORY:
#

# shellcheck disable=SC1090
source ~/bin/xSHELL/init
xrequirements whereis

whereis "$1"