#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: wttr
# Created: Tuesday, 2020/02/18 - 20:44:58
# Author.: @fbnmtz, fgm (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2024/12/09 - 17:41:22
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.3.64
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  > see whether of a city form terminal
# ############################################################################
# HISTORY:
#

# shellcheck disable=SC1090
source "$xSHELL_INIT"
xrequirements cut tr curl sed
xsetHome

WEATHER_URL=wttr.in
FILENAME=""

getFileName(){
	local location=$1
	FILENAME=$location.txt
	echo "$FILENAME"
}
getWTTR(){
	local location=$1
	local filename=$2
	if [ ! -f "$filename" ]; then
		curl -s "$WEATHER_URL/$location" > "$filename" && sed -i '$ d' "$filename"
	fi
}

if [ -n "$1" ]; then	
	city=$(echo "$@" | tr -s ' ' '-')

	FILENAME="$city.txt"
	if [ ! -f "$APP_HOME/$FILENAME" ]; then
		getWTTR "$city" "$APP_HOME/$FILENAME"
	fi
	cat "$APP_HOME"/"$FILENAME"
else
	for city in ${APP_HOME}/*; do
		FILENAME="${city}"
		if [ ! -f "$FILENAME" ]; then
			getWTTR "$city" "$FILENAME"
		fi
		cat "$FILENAME" || exit
		read -r
	done
fi
