#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: xhr
# Created: Wednesday, 2021/05/26 - 23:45:50
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Tuesday, 2023/08/22 - 09:27:47
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.3.26
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#
#

# shellcheck disable=SC1090
source ~/bin/xSHELL/init
use args
xarg --id -s,--size  --var "size+r" --desc "set number of columns"
xrun --xrequire-one --xversionrc --xcolors "$@"

case $1 in
  1) char="~" ;;
  2) char="*"  ;;
  3) char="-"  ;;
  4) char="+"  ;;
  5) char="." ;;
  5) char="/" ;;
  *) char="#"  ;;
esac

[ -z "$size" ] && size=80 
echo -n "# "
for i in $(seq 1 "$size"); do
  echo -n "$char"
done
echo