#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: xhr
# Created: Wednesday, 2021/05/26 - 23:45:50
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Thursday, 2023/08/24 - 22:15:49
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.4.38
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#
#

# shellcheck disable=SC1090
source ~/bin/xSHELL/init
use args
xarg --id -s,--size  --var "size+r" --desc "columns of header"
xarg --id -c,--char  --var "char+r" --desc "custom <char> for header"
xrun --xrequire-one --xversionrc --xcolors "$@"

if [ -z "$char" ]; then 
  case $1 in
    1) char="~" ;;
    2) char="*"  ;;
    3) char="-"  ;;
    4) char="+"  ;;
    5) char="." ;;
    6) char="/" ;;
    *) char="#"  ;;
  esac
fi

[ -z "$size" ] && size=80 
echo -n "# "
for i in $(seq 1 "$size"); do
  echo -n "$char"
done
echo