#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: xhr
# Created: Wednesday, 2021/05/26 - 23:45:50
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2025/01/26 - 13:05:23
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.5.72
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#
#

# shellcheck disable=SC1090
source "$xSHELL_INIT"
use args

xrequirements tput seq

xarg --id -s,--size    --var "size+r" --desc "columns of header"
xarg --id -c,--char    --var "char+r" --desc "custom <char> for header"
xarg --id -C,--comment --desc "add comment before header line"

xrun --xversionrc --xcolors "$@"

if [ -z "$char" ]; then 
  if [ -n "$1" ]; then
    case $1 in
      1) char="~"  ;;
      2) char="*"  ;;
      3) char="-"  ;;
      4) char="+"  ;;
      5) char="."  ;;
      6) char="/"  ;;
      *) char="$1" ;;
    esac
  else 
    char="#"
  fi
fi

# get curret terminal collumn size
[ -z "$size" ] && size=$(($(tput cols)-2))
# add shell comment before, if requested
[ "$xarg" == "C" ] && echo -n "# "
# print header line
for i in $(seq 1 "$size"); do
  echo -n "$char"
done
# break line at end
echo