#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: xip
# Created: Monday, 2022/01/31 - 20:28:15
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Friday, 2023/08/25 - 20:05:36
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.0.3.127
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# shellcheck disable=SC1090
source ~/bin/xSHELL/init
use args utils xiplib
xrequirements lshw grep aw tr ip curl

xarg --id -i,--interfaces   --var action:iface --desc "available interfaces"
xarg --id -a,--all          --var action:all   --desc "detailed information"
xarg --id -e,--external-ip  --var action:ext   --desc "external IP address"
xarg --header "interfaces / IP information" 
xrun --xreject-unknow --xversionrc --xcolors "$@"

case "$action" in
  iface) echo -e "${_IFACES[*]}\n" ;;
  all  ) ip a | grep -A2 "$_FILTER" | grep -v "inet6\|link\|valid_lft" ;;
  ext  ) _getIP ;;
esac