#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: xip
# Created: Monday, 2022/01/31 - 20:28:15
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Friday, 2023/06/30 - 04:20:36
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.0.2.111
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# shellcheck disable=SC1090
source ~/bin/xSHELL/init
use args utils
xrequirements lshw grep aw tr ip curl

xarg --id -i,--interfaces   --var action:interfaces --desc "available interfaces"
xarg --id -a,--all          --var action:all        --desc "detailed information"
xarg --id -e,--external-ip  --var action:external   --desc "external IP address"
xarg --header "interfaces / IP information" 
xrun --xreject-unknow --xversionrc --xcolors "$@"

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
_IFACES=$(lshw 2> /dev/null | grep -A5 interface | grep logical | aw 3 | tr -s '\n' ' ')
_FILTER="$(echo "${_IFACES[@]::-1}" | sed 's/ /\\|/g' )"

case "$action" in
  interfaces)  echo -e "${_IFACES[*]}\n" ;;
  all       ) ip a | grep -A2 "$_FILTER" | grep -v "inet6\|link\|valid_lft" ;;
  external  ) curl ifconfig.me ;;
esac