#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: xman
# Created: 2020/02/27 - 00:04:23
# Author.: @fbnmtz, fgm (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2023/08/14 - 20:03:15
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.0.4.154
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# SC1090: Can't follow non-constant source. Use a directive to specify location.
# shellcheck disable=SC1090        
source ~/bin/xSHELL/init
use args xman.lib

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
xrequirements find sed awk sort rofi man llppac
xsetHome

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
xarg --id -b,--binary --var m:bin,binary+r   --desc "binary to show man"
xarg --id -l,--list   --var m:list,list:true --desc "list already generated man"
xrun --xversionrc --xcolors "$@"

# check module activeted by flag
case "$m" in
  list) mList   ;;
  # bin ) mBinary ;;
  *   ) mBinary ;;
esac
