#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: xtranslate
# Created: Saturday, 2023/01/14 - 13:08:04
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Thursday, 2025/02/20 - 00:25:01
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.0.0.119
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  > script to translate  text 
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
# shellcheck disable=SC1090,SC2154    
source "$xSHELL_INIT"
use args colors
xrequirements curl jq xclip-cmd

clipboard_text=$(xclip-cmd -p)

_translate(){
    local text="$@"
    # Make the translation using curl 
    output=$(
        curl -s -A "Mozilla/5.0" -G \
            --data-urlencode "client=gtx" \
            --data-urlencode "sl=auto" \
            --data-urlencode "tl=en" \
            --data-urlencode "dt=t" \
            --data-urlencode "q=$text" \
            "http://translate.googleapis.com/translate_a/single"
    )
    # extract translation from json output
    translation="$(echo "$output" |  jq -r '.[0][0][0]')"
}

_to_clipboard(){ echo "$translation" | xclip-cmd > /dev/null; }

xarg --id -t,--text           --desc "set <text> to translate"    --var text+r
xarg --id -T,--text-clipboard --desc "fill <text> from clipboard"
xarg --id -c,--clipboard      --desc "save translation to clipboard"

xarg --header "translations using 'Google Translate'"

xrun --xrequire-one --xreject-unknown "$@"

xcase t "_translate $text"
xcase T "_translate $clipboard_text"
xcase c "_to_clipboard"

xsys.write "$translation"