#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: ytdl
# Created: Sunday, 2022/04/03 - 16:49:39
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Tuesday, 2023/06/20 - 00:37:24
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.3.86
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
# shellcheck disable=SC1090,SC2154    
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
source ~/bin/xSHELL/init    
use args ytdl.lib
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
xrequirements yt-dlp:youtube-dl cut sed

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
xarg --id -V,--video   --var flag:video,url+r        --desc "download video from YouTube url"    
xarg --id -a,--audio   --var flag:audio,url+r        --desc "download audio from YouTube url"     
xarg --id -e,--extract --var flag:extract,filename+r --desc "extract audio from a video file"      
xarg --header "download a video/audio from a given url on YouTube"
    
xrun --xreject-unknow --xrequire-one --xversionrc --xcolors "$@"    
    
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
case "$flag" in    
    video  ) runCMD video "$url" ;;
    audio  ) runCMD audio "$url" ;;
    extract)
        audio=$(echo "$filename" | tr -s ' ' '-' | cut -d '.' -f1)
        ffmpeg -i "$filename" -f mp3 -ab 192000 -vn "${audio}".mp3 
    ;;
esac    
