#!/usr/bin/env bash
#
# ############################################################################
# Project: scripts (none)
# File...: ytdl
# Created: Sunday, 2022/04/03 - 16:49:39
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2024/12/09 - 17:38:37
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.4.96
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
# shellcheck disable=SC1090,SC2154    
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
source "$xSHELL_INIT"    
use args ytdl.lib
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
xrequirements yt-dlp:youtube-dl cut sed

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
xarg --id -V,--video   --var flag:v,url+r      --desc "download video from YouTube url"    
xarg --id -a,--audio   --var flag:a,url+r      --desc "download audio from YouTube url"     
xarg --id -e,--extract --var flag:e,filename+r --desc "extract audio from a local video file"      
xarg --header "download a video/audio from a given url on YouTube"
    
xrun --xreject-unknow --xrequire-one --xversionrc --xcolors "$@"    
    
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
case "$flag" in    
    v) runCMD video "$url" ;;
    a) runCMD audio "$url" ;;
    e) ytExtract "$url"    ;;
esac    
